apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cassandra-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gaia-cassandra
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-helm
        namespace: flux-system
      version: 0.2.0
  interval: 2m0s
  releaseName: cassandra-release
  targetNamespace: flux2-gad
  values:
    image:
      repository: sekidocker.rnd.ki.sw.ericsson.se/proj-git-aes-gpr-3pp-del/eric-data-wide-column-database-cd
      tag: 3.7.0-6
      pullPolicy: IfNotPresent
      pullSecrets: docreg
    jmxExporter:
      enabled: false
    persistence:
      enabled: true
      size: 16Gi
      storageClass: default
    replicaCount: 3
    resources:
      limits:
        cpu: 3
        memory: 3Gi
      requests:
        cpu: 0.5
        memory: 1Gi