apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: flux-staging
  interval: 30s
  targetNamespace: devops-toolkit
  values:
    image:
      tag: 2.9.9
    ingress:
      host: flux-staging.devops-toolkit.10.96.0.1.xip.io